### ISSUE TITLE
Error when trying to sell

### ISSUE THREAD

**Issue by sheremetyev** [tzConnectBerlin/prediction-market-ui#528]
**Describe the bug**
Error `contract.counter_in_the_past`.

**To Reproduce**
Cannot reproduce reliably but this is what I did before getting the error.

1. Open one of the markets in https://f1-prediction-market.vercel.app/.
2. Buy a few tokens and wait for transaction to be processed.
3. Buy some tokens again.
4. Quickly try sell some tokens from your existing balance.
5. See error

**Expected behavior**
Transaction for sell to succeed of show more meaningful error.

**Screenshots**

<img width="1280" alt="Screenshot 2021-09-16 at 13 28 33" src="https://user-images.githubusercontent.com/602025/133622633-a9147e24-cfce-4bbe-9d0b-deabd18f14b5.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.5.2
 - Browser: Chrome 93
 - Version: not sure where it's displayed, error happened around 2021-09-16 13:28 BST

**Additional context**

Perhaps depends on activity of other users buying/selling concurrently around the same time?

**Comment by tlebon** [comment]
this is an issue with how tezos handles transactions. If previous transactions have not yet been posted to a block you are unable to send a new transaction.
